---
- hosts: all

  tasks:

  - name: Read in role variables
    include_vars:
      dir: 'roles/{{ item }}/vars'
      files_matching: 'main.yml'
    with_fileglob:
      - "roles/*"
    register: result

  - name: Apply override settings, if available
    include_vars: '/etc/rocknsm/config.yml'
    ignore_errors: true
    failed_when: false

  - name: Create config directory
    file:
      state: directory
      owner: root
      group: root
      mode:  0755
      path: /etc/rocknsm

  - name: Render template
    template:
      backup: yes
      src: rock_config.yml.j2
      dest: /etc/rocknsm/config.yml
      owner: root
      group: root
      mode: 0644
