---
- hosts: all

  tasks:
  
  - name: Apply override settings, if available
    include_vars: '/etc/rocknsm/config.yml'

  - name: Create config directory
    file:
      state: directory
      owner: root
      group: root
      mode:  0755
      path: /etc/rocknsm

  - name: Render template
    template:
      backup: yes
      src: rock_config.yml.j2
      dest: /etc/rocknsm/config.yml
      owner: root
      group: root
      mode: 0644
