---
- hosts: sensors

- import_playbook: all.yml
    
  tasks:

  - include_role:
      name: common
  
  - include_role:
      name: common_sensor
      
    ######################################################
    ##################  GeoIP Databases  #################
    ######################################################
  - name: Configure GeoIP Update
    copy: src=GeoIP.conf dest=/etc/GeoIP.conf

    # There's an issue w/ geoipupdate when env is empty
  - name: Update GeoIP
    shell: >
      if [ "x$HTTP_PROXY" == "x" ]; then
          unset HTTP_PROXY;
      fi
      if [ "x$http_proxy" == "x" ]; then
          unset http_proxy;
      fi
      if [ "x$HTTPS_PROXY" == "x" ]; then
          unset HTTPS_PROXY;
      fi
      if [ "x$https_proxy" == "x" ]; then
          unset https_proxy;
      fi
      /usr/bin/geoipupdate
    args:
      creates: /usr/share/GeoIP/GeoLiteASNum.dat
    register: result
    failed_when: (result.rc != 0) and (result.rc != 1)

  - name: Create GeoIP symlinks
    file:
      src: "/usr/share/GeoIP/{{ item.src }}"
      dest: "/usr/share/GeoIP/{{ item.dest }}"
      force: yes
      state: link
    with_items:
      - { src: 'GeoLiteCity.dat', dest: 'GeoIPCity.dat' }
      - { src: 'GeoLiteCountry.dat', dest: 'GeoIPCountry.dat' }
      - { src: 'GeoLiteASNum.dat', dest: 'GeoIPASNum.dat' }
      - { src: 'GeoLiteCityv6.dat', dest: 'GeoIPCityv6.dat' }
      
  - include_role:
      name: docker
    when: containerized_install

  - include_role:
      name: suricata        

  - include_role:
      name: zookeeper
      
  - include_role:
      name: kafka
      
  - include_role:
      name: elasticsearch  
      
  - include_role:
      name: logstash
      
  - include_role:
      name: filebeats

  - include_role:
      name: bro
      
  - name: kibana
    include_role:
      name: kibana
      
  # TODO NEEDS TO BE TESTED     
#  - include_role:
#      name: stenographer
      
  - include_role:
      name: nginx
   
