---

- hosts: sensors

  roles:
    - common_sensor
    - { role: suricata, when: with_suricata }
    - { role: kafka, when: with_kafka }
    - { role: zookeeper, when: with_zookeeper }
    - { role: filebeats, when: with_filebeats }
    - { role: bro, when: with_bro }