---

- import_playbook: all.yml    

- hosts: servers
    
  tasks:

  - include_role:
      name: common
      
  - include_role:
      name: docker
      when: containerized_install

  - include_role: 
      name: portainer 
    when: containerized_install and with_portainer

  - include_role: 
      name: harbor 
      when: containerized_install and with_harbor
 
  - include_role:
      name: zookeeper
      when: with_zookeeper
      
  - include_role:
      name: elasticsearch
      when: with_elasticsearch      
      
  - include_role:
      name: logstash
      when: with_logstash
      
  - name: kibana
    include_role:
      name: kibana
      when: with_kibana
      
  # TODO NEEDS TO BE TESTED     
#  - include_role:
#      name: stenographer
      
  - include_role:
      name: nginx
      when: with_nginx
